export const PERMISSIONS = {
  // USER
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_VIEW: "USER_VIEW",
  USER_APPROVE: "USER_APPROVE",
  USER_STATUS_UPDATE: "USER_STATUS_UPDATE",

  // ROLE
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",
  ROLE_VIEW  : "ROLE_VIEW",
  ROLE_ASSIGN: "ROLE_ASSIGN",
  ROLE_REMOVE: "ROLE_REMOVE",

  // PERMISSION
  PERMISSION_VIEW: "PERMISSION_VIEW",
  PERMISSION_ASSIGN: "PERMISSION_ASSIGN",
  PERMISSION_REMOVE: "PERMISSION_REMOVE",

  // LEAD
  LEAD_CREATE: "LEAD_CREATE",
  LEAD_UPDATE: "LEAD_UPDATE",
  LEAD_DELETE: "LEAD_DELETE",
  LEAD_VIEW: "LEAD_VIEW",
  LEAD_VIEW_ALL: "LEAD_VIEW_ALL",
  LEAD_ASSIGN: "LEAD_ASSIGN",
  LEAD_STATUS_UPDATE: "LEAD_STATUS_UPDATE",

  // DEAL
  DEAL_CREATE: "DEAL_CREATE",
  DEAL_UPDATE: "DEAL_UPDATE",
  DEAL_DELETE: "DEAL_DELETE",
  DEAL_VIEW: "DEAL_VIEW",
   DEAL_VIEW_ALL: "DEAL_VIEW_ALL",
  DEAL_ASSIGN: "DEAL_ASSIGN",
  DEAL_STAGE_UPDATE: "DEAL_STAGE_UPDATE",

  // SALES
  SALE_CREATE: "SALE_CREATE",
  SALE_VIEW: "SALE_VIEW",
  SALE_VIEW_ALL: "SALE_VIEW_ALL",
  SALE_PAYMENT_UPDATE: "SALE_PAYMENT_UPDATE",
  SALE_SUMMARY_VIEW: "SALE_SUMMARY_VIEW",

  // TARGET
  TARGET_CREATE: "TARGET_CREATE",
  TARGET_UPDATE: "TARGET_UPDATE",
  TARGET_DELETE: "TARGET_DELETE",
  TARGET_VIEW: "TARGET_VIEW",
  TARGET_VIEW_ALL: "TARGET_VIEW_ALL",
  TARGET_TEAM_PERFORMANCE: "TARGET_TEAM_PERFORMANCE",
  TARGET_USER_PERFORMANCE: "TARGET_USER_PERFORMANCE",

  // REPORT
  REPORT_VIEW: "REPORT_VIEW",
  REPORT_SALES: "REPORT_SALES",
  REPORT_CONVERSION: "REPORT_CONVERSION",
  REPORT_LOST_DEALS: "REPORT_LOST_DEALS",
  REPORT_DASHBOARD: "REPORT_DASHBOARD",
};